# Production environment override
services:
  php:
    build:
      context: .
      target: frankenphp_prod
    environment:
      FRANKENPHP_CONFIG: ""
#      CADDY_SERVER_EXTRA_DIRECTIVES: "tls /etc/caddy/certs/tls.pem /etc/caddy/certs/tls.key"
    volumes:
      - /frankenphp/certs:/etc/caddy/certs:ro
