# Production environment override
services:
  php:
    build:
      context: .
      target: frankenphp_prod
    volumes:
      - /frankenphp/certs:/etc/caddy/certs:ro
    env_file:
      - .env.prod.local
